import { Inter } from "next/font/google";
// import "./globals.css";
import "./styles.css";
import "bootstrap/dist/css/bootstrap.css";
// import BootstrapClient from "./components/BootstrapClient";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Beat Link",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
